; WIX1003 LAB ASSIGNMENT
; TRAFFIC LIGHT CONTROL SYSTEM
; P0 = LED DISPLAY (TIMER)
; P1 = RED LIGHT
; P2 = YELLOW LIGHT
; P3 = GREEN LIGHT

	ORG 	00H
	AJMP 	MAIN

MAIN:	MOV 	A,#0FFH	; SET P3 IN OFF CONDITION
	MOV 	P3,A
	MOV 	A,#0FFH	; SET P2 IN OFF CONDITION
	MOV 	P2,A
	MOV 	A,#0AAH	; SET P1 IN ON CONDITION (SPECIFIC TO BIT 0,2,4,6)
	MOV 	P1,A
	MOV	A,#00H	; SET P0 IN OFF CONDITION
	MOV	P0,A
	ACALL 	DELAYB	; DELAY 3 SECONDS 

START:
; 1ST GREEN LIGHTS UP
	MOV 	P1,#0ABH
	MOV 	P3,#0FEH
	ACALL 	DELAYA	; DELAY 9 SECONDS 

; 1ST YELLOW LIGHTS UP
	MOV 	P3,#0FFH
	MOV 	P2,#0FEH
	ACALL 	DELAYB	; DELAY 3 SECONDS

; 1ST RETURN TO RED LIGHT
	MOV 	P2,#0FFH
	MOV 	P1,#0AAH
	ACALL 	DELAYB	; DELAY 3 SECONDS

; 2ND GREEN LIGHTS UP
	MOV 	P1,#0AEH
	MOV 	P3,#0FBH
	ACALL 	DELAYA	; DELAY 9 SECONDS

; 2ND YELLOW LIGHTS UP
	MOV 	P3,#0FFH
	MOV 	P2,#0FBH
	ACALL 	DELAYB	; DELAY 3 SECONDS

; 2ND RETURN TO RED LIGHT
	MOV 	P2,#0FFH
	MOV 	P1,#0AAH
	ACALL 	DELAYB	; DELAY 3 SECONDS

; 3RD GREEN LIGHTS UP
	MOV 	P1,#0BAH
	MOV 	P3,#0EFH
	ACALL 	DELAYA	; DELAY 9 SECONDS

; 3RD YELLOW LIGHTS UP
	MOV 	P3,#0FFH
	MOV 	P2,#0EFH
	ACALL 	DELAYB	; DELAY 3 SECONDS

; 3RD RETURN TO RED LIGHT
	MOV 	P2,#0FFH
	MOV 	P1,#0AAH
	ACALL 	DELAYB	; DELAY 3 SECONDS

; 4TH GREEN LIGHTS UP
	MOV 	P1,#0EAH
	MOV 	P3,#0BFH
	ACALL 	DELAYA	; DELAY 9 SECONDS

; 4TH YELLOW LIGHTS UP
	MOV 	P3,#0FFH
	MOV 	P2,#0BFH
	ACALL 	DELAYB	; DELAY 3 SECONDS

; 4TH RETURN TO RED LIGHT
	MOV 	P2,#0FFH
	MOV 	P1,#0AAH
	ACALL 	DELAYB	; DELAY 3 SECONDS
	AJMP 	START	; ABSOLUTE JUMP TO START

; DELAY SBUROUTINE
DELAY:	MOV 	R1,#009H 
	MOV 	R2,#007H
	MOV	R3,#005H 
DELAY1:	DJNZ 	R3,DELAY1
	DJNZ 	R2,DELAY1
	DJNZ	R1,DELAY1
	RET

; DELAY 9 SECONDS
DELAYA:	MOV 	P0,#67H
	ACALL	DELAY
	MOV 	P0,#7FH
	ACALL	DELAY
	MOV 	P0,#7H
	ACALL	DELAY
	MOV 	P0,#7DH
	ACALL	DELAY
	MOV 	P0,#6DH
	ACALL	DELAY
	MOV	P0,#66H
	ACALL	DELAY
	MOV	P0,#4FH
	ACALL	DELAY
	MOV	P0,#5BH
	ACALL	DELAY
	MOV	P0,#6H
	ACALL	DELAY
	RET

; DELAY 3 SECONDS
DELAYB:	MOV	P0,#4FH
	ACALL	DELAY
	MOV	P0,#5BH
	ACALL	DELAY
	MOV	P0,#6H
	ACALL	DELAY
        RET
        
	END